steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect and update code on VM
    entrypoint: bash
    args:
    - '-c'
    - |
      mkdir -p ~/root/.ssh && \\
      gcloud secrets versions access latest --secret=TEST_PRIVATE > ~/root/.ssh/id_rsa && \\
      chmod 600 ~/root/.ssh/id_rsa && \\
      gcloud secrets versions access latest --secret=TEST_PUB > ~/root/.ssh/id_rsa.pub && \\
      chmod 600 ~/root/.ssh/id_rsa.pub && \\
      set -x && \\
      gcloud compute ssh ronnjoshua@test-instance --ssh-key-file=~/root/.ssh/id_rsa --project=business-books-global --zone=us-central1-a --command='sudo sh -c "cd /home/ron/CGE-test && git fetch && git reset --hard HEAD && git merge '@{u}' && git pull origin main "'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Reboot VM
    entrypoint: bash
    args:
    - '-c'
    - |
      gcloud compute instances reset test-instance --project=business-books-global --zone=us-central1-a
options:
  logging: CLOUD_LOGGING_ONLY
